### ISSUE TITLE
Support of Tornado >3

### ISSUE THREAD

**Issue by guyzmo** [guyzmo/event-source-library#10]
The following error gets thrown when launching eventsource with last version of tornado (3.0.1):

```
DEBUG:eventsource.listener:get(XXX,poll)
DEBUG:eventsource.listener:set_connected(XXX)
ERROR:tornado.application:Uncaught exception GET /poll/XXX (::1)
HTTPRequest(protocol='http', host='localhost:8000', method='GET', uri='/poll/XXX', version='HTTP/1.1', remote_ip='::1', body='', headers={'Host': 'localhost:8000', 'Content-Type': 'text/event-stream', 'Accept-Encoding': 'gzip,deflate', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (compatible; pycurl)'})
Traceback (most recent call last):
  File ".../event-source-library/eggs/tornado-3.0.1-py2.7.egg/tornado/web.py", line 1055, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File ".../event-source-library/eggs/tornado-3.0.1-py2.7.egg/tornado/web.py", line 1178, in wrapper
    result = method(self, *args, **kwargs)
  File ".../event-source-library/eventsource/listener.py", line 346, in get
    self._lock[target].get(self._event_loop)
  File ".../event-source-library/eggs/toro-0.5-py2.7.egg/toro/__init__.py", line 186, in get
    future = _TimeoutFuture(deadline, self.io_loop)
  File ".../event-source-library/eggs/toro-0.5-py2.7.egg/toro/__init__.py", line 64, in __init__
    self._timeout_handle = io_loop.add_timeout(deadline, callback)
  File ".../event-source-library/eggs/tornado-3.0.1-py2.7.egg/tornado/ioloop.py", line 681, in add_timeout
    timeout = _Timeout(deadline, stack_context.wrap(callback), self)
  File ".../event-source-library/eggs/tornado-3.0.1-py2.7.egg/tornado/ioloop.py", line 740, in __init__
    raise TypeError("Unsupported deadline %r" % deadline)
TypeError: Unsupported deadline <bound method EventSourceHandler._event_loop of <eventsource.listener.EventSourceHandler object at 0x1f63150>>
ERROR:tornado.access:500 GET /poll/XXX (::1) 2.51ms
DEBUG:eventsource.listener:push_keepalive()
ERROR:tornado.application:Uncaught exception GET /poll/XXX (::1)
HTTPRequest(protocol='http', host='localhost:8000', method='GET', uri='/poll/XXX', version='HTTP/1.1', remote_ip='::1', body='', headers={'Host': 'localhost:8000', 'Content-Type': 'text/event-stream', 'Accept-Encoding': 'gzip,deflate', 'Accept': '*/*', 'User-Agent': 'Mozilla/5.0 (compatible; pycurl)'})
Traceback (most recent call last):
  File ".../event-source-library/eggs/tornado-3.0.1-py2.7.egg/tornado/web.py", line 1055, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File ".../event-source-library/eggs/tornado-3.0.1-py2.7.egg/tornado/web.py", line 1178, in wrapper
    result = method(self, *args, **kwargs)
  File ".../event-source-library/eventsource/listener.py", line 178, in push_keepalive
    self.write(": keepalive %s\r\n\r\n" % (unicode(time.time())))
  File ".../event-source-library/eggs/tornado-3.0.1-py2.7.egg/tornado/web.py", line 513, in write
    raise RuntimeError("Cannot write() after finish().  May be caused "
RuntimeError: Cannot write() after finish().  May be caused by using async operations without the @asynchronous decorator.
ERROR:tornado.general:Cannot send error response after headers written
DEBUG:eventsource.listener:get(XXX,poll)
```

Until this issue is solved, I'm setting up a branch that works with up to date tornado, and make 
the master branch stuck with tornado 2.2.1, which is the last version of tornado ESL has been tested with.

problems arise at [listener.py:346](https://github.com/guyzmo/event-source-library/blob/master/eventsource/listener.py#L346) and at [listener.py:178](https://github.com/guyzmo/event-source-library/blob/master/eventsource/listener.py#L178), there's an error on how failure is being dealt.

**Comment by salmanham** [comment]
Could you please let me know how you ran into this issue. I've been running the samples provided and have not had an issue with tornado 3.2 or 3.0.1.

**Comment by salmanham** [comment]
After looking into this a little more, this seems to be an issue with toro 0.5 and not tornado, as the get method of AsyncResult does not have a callback anymore and only a deadline.

**Comment by guyzmo** [comment]
I'm sorry, but I have been working on that project about 3 years ago, and I almost entirely forgot what it was about :-) Glad you've been able to dig a bit into it. If needed I can try to use again by event-source library ;-)

Otherwise we might just close the ticket

**Comment by guyzmo** [comment]
Hello! Have you got any idea on how we could fix this, so I could clean the issues list, and run it with a more recent tornado? :-)

**Comment by salmanham** [comment]
I'm sorry, my project got cancelled and I moved onto something else so I
don't remember.

**Comment by osmoc** [comment]
I'm interested in this too - any ideas how to get this running with tornado 4.4.x?

**Comment by osmoc** [comment]
Hmm, just replaced the line in setup.py and got test examples running with tornado 4.4.1 - at least I think so (not an expert on pip and other python tools), is there a way for eventsource to programmatically check which version of tornado it's actually using so it can be reported on -v?

**Comment by osmoc** [comment]
FYI: sent PR with bumped version requirements - works for me :)

**Comment by jacobborisov** [comment]
I think we must move out of Toro completely. At this time it's officially deprecated and all features seems to be merged into Tornado:

> [Toro is completed and deprecated; its features have been merged into Tornado. Development of locks and queues for Tornado coroutines continues in Tornado itself.](https://pypi.python.org/pypi/toro/)

Although current eventsource code seems to be usable with Tornado 4.* and Toro 0.4 branches, i consider it's not a good idea to be dependent on a very old version of deprecated library in any case.

If I understand your design logic properly, now `AsyncResult` may be simply replaced by `tornado.concurrent.Future`. So I've committed (#20) corresponded changes, please check it out.

**Comment by osmoc** [comment]
Excellent work, see my comment in #18 for details.

**Comment by guyzmo** [comment]
merged!
