### ISSUE TITLE
doubled events

### ISSUE THREAD

**Issue by osmoc** [guyzmo/event-source-library#18]
When running examples outlined in a readme I've got the same output twice from client:

```
eventsource-client test -r 5000 -P 8888
INFO:eventsource.client:received Event<0,ping,{"B": "XXX"}>
INFO:eventsource.client:received Event<0,ping,{"B": "XXX"}>
```

Does this mean that there are 2 events have arrived or it's just artefact of debugging?

**Comment by guyzmo** [comment]
well, all I can tell is that this line is being called each time the event receiving callback is triggered (and is the default callback, which is the case for the ping action). So what it means it's that `handle_stream()` is finishing twice with the same `Event` object (you can check it by increasing verbosity `-v`).  Basically `handle_stream()` is there to reconstruct data that has been split in several "datagrams" over the Event Source protocol.

**Comment by jacobborisov** [comment]
I've faced with the similar issue when i try to use this lib to send events for a web browser instead of using the console utility. I've found a possible solution that works in my case.

@osmoc please could you check if it solves your problem? #20 I'm not sure this change is safe and wouldn't broke some other things.

**Comment by guyzmo** [comment]
@jacobborisov I might be ok with accepting the merge, though I'm not sure why I wrote [that comment](https://github.com/jacobborisov/event-source-library/blob/9b537748aeda937811e8939399832149adccad53/eventsource/listener.py#L209,L209), but I must have had a good reason to add a note saying that it *shall be reset on set() call* 😀

Though, when ready the code and where you've put that change, I believe it can make sense, as it's resetting the `_ready` state just before looping over.

It's sad I did not write any tests then (lack of time, and for my use case, it being hackish was ok) which would help a lot to fix that can of edge cases ☺

**Comment by guyzmo** [comment]
I'll wait a bit to see if @osmoc can test and approve it's fixing the issue for him as well. And then I'll merge, thanks @jacobborisov !

**Comment by osmoc** [comment]
Pardon the delay, been swamped by other stuff. I've tested @jacobborisov fixes:
+ it's indeed fixes both double-events and toro dependency
- it does not touch buildout.cfg and setup.py

Overall, please merge it, I can re-base my pull request on top of @jacobborisov work and fix minor issues.

Thanks for the great work!

**Comment by guyzmo** [comment]
ok I'll do just that! Please bear with me a few more days, though.

**Comment by guyzmo** [comment]
merged!
